# Generated by Django 3.0.4 on 2020-03-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=500)),
                ('total_cases', models.IntegerField(default=0)),
                ('new_cases', models.CharField(max_length=500)),
                ('total_deaths', models.IntegerField(default=0)),
                ('new_deaths', models.CharField(max_length=500)),
                ('total_recovered', models.IntegerField(default=0)),
                ('active_cases', models.IntegerField(default=0)),
                ('serious_critical', models.IntegerField(default=0)),
                ('tot_cases', models.IntegerField(default=0)),
                ('tot_deaths', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
