# Generated by Django 3.0.4 on 2020-03-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_coviddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='active_cases',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='serious_critical',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='tot_cases',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='tot_deaths',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='total_cases',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='total_deaths',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='total_recovered',
            field=models.CharField(max_length=500),
        ),
    ]
